# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #- name: checkout
    #  uses: actions/checkout@v1

    - name: run scripts from remote host
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: cd /var/www/html && /bin/sh ./deploy.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
      env:
        CI: true